/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PetType = IDL.Variant({
  'cat' : IDL.Null,
  'dog' : IDL.Null,
  'fox' : IDL.Null,
  'penguin' : IDL.Null,
  'custom' : IDL.Text,
  'default' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const Session = IDL.Record({
  'duration' : IDL.Nat,
  'focusType' : IDL.Variant({
    'creative' : IDL.Null,
    'work' : IDL.Null,
    'exercise' : IDL.Null,
    'study' : IDL.Null,
    'default' : IDL.Null,
  }),
  'petType' : PetType,
  'timestamp' : Time,
});
export const UserSettings = IDL.Record({
  'wastedPlatforms' : IDL.Vec(IDL.Text),
  'darkMode' : IDL.Bool,
  'petType' : PetType,
  'focusDuration' : IDL.Nat,
  'breakDuration' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSession' : IDL.Func(
      [
        PetType,
        IDL.Nat,
        IDL.Variant({
          'creative' : IDL.Null,
          'work' : IDL.Null,
          'exercise' : IDL.Null,
          'study' : IDL.Null,
          'default' : IDL.Null,
        }),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessions' : IDL.Func([IDL.Principal], [IDL.Vec(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSessionCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserSettings)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PetType = IDL.Variant({
    'cat' : IDL.Null,
    'dog' : IDL.Null,
    'fox' : IDL.Null,
    'penguin' : IDL.Null,
    'custom' : IDL.Text,
    'default' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const Session = IDL.Record({
    'duration' : IDL.Nat,
    'focusType' : IDL.Variant({
      'creative' : IDL.Null,
      'work' : IDL.Null,
      'exercise' : IDL.Null,
      'study' : IDL.Null,
      'default' : IDL.Null,
    }),
    'petType' : PetType,
    'timestamp' : Time,
  });
  const UserSettings = IDL.Record({
    'wastedPlatforms' : IDL.Vec(IDL.Text),
    'darkMode' : IDL.Bool,
    'petType' : PetType,
    'focusDuration' : IDL.Nat,
    'breakDuration' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSession' : IDL.Func(
        [
          PetType,
          IDL.Nat,
          IDL.Variant({
            'creative' : IDL.Null,
            'work' : IDL.Null,
            'exercise' : IDL.Null,
            'study' : IDL.Null,
            'default' : IDL.Null,
          }),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessions' : IDL.Func([IDL.Principal], [IDL.Vec(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSessionCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserSettings)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };