/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PetType = { 'cat' : null } |
  { 'dog' : null } |
  { 'fox' : null } |
  { 'penguin' : null } |
  { 'custom' : string } |
  { 'default' : null };
export interface Session {
  'duration' : bigint,
  'focusType' : { 'creative' : null } |
    { 'work' : null } |
    { 'exercise' : null } |
    { 'study' : null } |
    { 'default' : null },
  'petType' : PetType,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'wastedPlatforms' : Array<string>,
  'darkMode' : boolean,
  'petType' : PetType,
  'focusDuration' : bigint,
  'breakDuration' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSession' : ActorMethod<
    [
      PetType,
      bigint,
      { 'creative' : null } |
        { 'work' : null } |
        { 'exercise' : null } |
        { 'study' : null } |
        { 'default' : null },
      boolean,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSessions' : ActorMethod<[Principal], Array<Session>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSessionCount' : ActorMethod<[Principal], bigint>,
  'getUserSettings' : ActorMethod<[Principal], [] | [UserSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];